@auth
    <x-layouts.dashboard>
        @include('live._show-content')
    </x-layouts.dashboard>
@else
    <x-layouts.live-guest>
        @include('live._show-content')
    </x-layouts.live-guest>
@endauth
